spring.application.name=vinylshop-controller

PSQL_DATABASENAME=vinylshop2
PSQL_USERNAME=postgres
PSQL_USERPASSWORD=password


spring.datasource.url=jdbc:postgresql://localhost:5432/vinylshop2
spring.datasource.username=postgres
spring.datasource.password=password

#jpa instellingen
spring.jpa.show-sql=true

#genereer database structuur
spring.jpa.generate-ddl=true
#Bij het inleveren moet deze op 'Update' staan!!!
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always

#data.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect